### ISSUE TITLE
Exception: Did not find the display name in the profile page

### ISSUE THREAD

**Issue by magalive1991** [pe-st/garmin-connect-export#100]
Hello here,
I use this script for quite a while now every week to download my latest Garmin activities and it was working well, but for a couple of weeks I get the following error. Anyone encountered the same and would have any idea how to solve this ? Thanks a lot for your help !

Welcome to Garmin Connect Exporter!
[WARNING] Output directory [hidden] already exists. Will skip already-downloaded files and append to the CSV file.
Connecting to Garmin Connect... Done.
Requesting Login ticket... Done. Ticket=[hidden]
Authenticating... Done.
Getting display name...Traceback (most recent call last):
  File "[hidden]\gcexport.py", line 1343, in <module>
    main(sys.argv)
  File "[hidden]\gcexport.py", line 1297, in main
    userstats_json = fetch_userstats(args)
  File "[hidden]\gcexport.py", line 948, in fetch_userstats
    display_name = extract_display_name(profile_page)
  File "[hidden]\gcexport.py", line 973, in extract_display_name
    raise Exception('Did not find the display name in the profile page.')
Exception: Did not find the display name in the profile page.

**Comment by telemaxx** [comment]
Hi, you should use the latest Version. this solved it for me.

**Comment by magalive1991** [comment]
Thanks it's working now with the latest version ! (Will try that first next time I have an issue^^) Thanks!

**Comment by SimonBaars** [comment]
@pe-st This can be closed :)
