### ISSUE TITLE
HTTP Error 402: Payment Required 

### ISSUE THREAD

**Issue by andersfrisk** [pe-st/garmin-connect-export#102]
Don't really understand how this is working, but got this error now after not using the script for a couple of months - is it a known error?

old script? old python? old user ;) ?

  File "Python\Python311\Lib\urllib\request.py", line 643, in http_error_default 
    raise HTTPError(req.full_url, code, msg, hdrs, fp) 
**urllib.error.HTTPError: HTTP Error 402: Payment Required**

**Comment by telemaxx** [comment]
maybe you're script is to old. I had also to upgrade my script some month ago.
the new version used a module "garth", must be installed as descriped in the Doku.

**Comment by pe-st** [comment]
I'm closing this one, assuming the lack of feedback after telemaxx' comment means that the problem is gone. Feel free to reopen the issue though, mentioning the script version and best also an excerpt of the `gxexport.log` file
