### ISSUE TITLE
mail notification

### ISSUE THREAD

**Issue by prolibre** [pe-st/garmin-connect-export#103]
Hello,

For a few days now I've been getting an email every time I connect to the script. Is it possible to store a cookie to avoid this email each time I export ?

Thanks and have a nice day !

**Comment by pe-st** [comment]
The script itself does not send emails or use cookies, but maybe Garmin Connect itself. What is the email about? Who is the sender?

**Comment by prolibre** [comment]
@pe-st I misspoke (the translator). It's Garmin that sends me a message each time the script is used (cron): "We've noticed a connection to your account from a new location."

**Comment by prolibre** [comment]
Well, as I don't always receive these emails, I'm closing this ticket. Maybe Garmin is doing some updates of its own.
