### ISSUE TITLE
Expected xx activities, got 0

### ISSUE THREAD

**Issue by DrMoebius** [pe-st/garmin-connect-export#105]
The tool always worked brilliantly, but I haven't used in quite a while, got a new Laptop as well.

So after reinstalling and sorting out errors due to pip and garth and running everything now in a venv with garth: (redacted my username/mail)
`/Users/redacted/venv/bin/python3 /Users/redacted/Documents/Tools/garmin-connect-export-develop/gcexport.py -d /Users/redacted/Documents/Fitness/new --subdir {YYYY}/{MM} -ot --desc -c 15 --username redacted@gmail.com -v`

This is what I then get, from what I can tell the login worked, but then no activities were downloaded
```
[...]
[INFO] Requesting Login ticket
Requesting Login ticket... Done. Ticket=ST-2485499-BolHLM1Z17ngDfb6WDIk-xxx
[INFO] Authentication URL https://connect.garmin.com/modern/activities?ticket=ST-2485499-BolHLM1Z17ngDfb6WDIk-xxx
Authenticating... Done.
[INFO] Profile page https://connect.garmin.com/modern/profile
Getting display name... Done. displayName=redacted
[INFO] Userstats page https://connect.garmin.com/modern/proxy/userstats-service/statistics/redacted
Fetching user stats... Done.
[INFO] Activity list URL https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities?start=0&limit=15
Querying list of activities 1..15... Done.
[INFO] Expected 15 activities, got 0.
Done!
```

**Comment by chwunder** [comment]
anyone else has the same issue?

**Comment by chwunder** [comment]
can you check out the latest main @DrMoebius. After that, for me it worked again

**Comment by DrMoebius** [comment]
Thank you for your help @chwunder , I am an idiot. Instead of calling the latest version of the script that uses Garth I was calling an older local version. Everything works again.
