### ISSUE TITLE
List of supported activity types?

### ISSUE THREAD

**Issue by dm7500** [pe-st/garmin-connect-export#106]
I know we can filter the activity types via `-tf`. However, I don't see a list or reference anywhere for what codes mean what. I tried checking the Garmin site, but the reference in the URL shows as `https://connect.garmin.com/modern/activities?activityType=running`, which doesn't match the numbered examples in the docs for this project.

Anyone have a reference for this, or can point me in the right direction?

**Comment by pe-st** [comment]
Hello

When you use your browser's developer tools, you can see that it loads a JSON file with all the types from `https://connect.garmin.com/activity-service/activity/activityTypes` (but the link doesn't work outside the context of Garmin Connect, I get a 404 when pasting it directly in the browser), and with the browser's developer tools you can copy or save the response.

There is a stored version of this file (it can get out of date as it's not updated automatically) at https://github.com/pe-st/garmin-connect-export/blob/master/json/activityTypes.json

Here are the first few lines, giving you type `1` for "running" and `2` for "cycling":

```
[
    {
        "typeId": 1,
        "typeKey": "running",
        "parentTypeId": 17,
        "isHidden": false,
        "trimmable": true,
        "restricted": false
    },
    {
        "typeId": 2,
        "typeKey": "cycling",
        ...
```

Hope that helps

**Comment by dm7500** [comment]
Exactly what I needed. Thank you!
