### ISSUE TITLE
500 error with -c all

### ISSUE THREAD

**Issue by pmatos** [pe-st/garmin-connect-export#11]
With `-c all` to download all my history once I am downloading activities all the way back to 2013 I get:
```
Traceback (most recent call last):
  File "gcexport.py", line 710, in <module>
    main(sys.argv)
  File "gcexport.py", line 694, in main
    export_data_file(str(a['activityId']), activity_details, args)
  File "gcexport.py", line 499, in export_data_file
    raise Exception('Failed. Got an unexpected HTTP error (' + str(e.code) + download_url + ').')
Exception: Failed. Got an unexpected HTTP error (500http://connect.garmin.com/proxy/download-service/files/activity/320606384).
```

I guess I can't download activities that old maybe. Or maybe not so many in a single call. Is there a way to `--retry` it?

**Comment by pe-st** [comment]
Hi @pmatos 
Usually you can just relaunch your command and it should continue where it stopped.
I've had no problems downloading more than 1000 activities in one go, how many activities do you have?

**Comment by pe-st** [comment]
Please feel free to reopen the issue if the problem persists.
