### ISSUE TITLE
Doesn't skip existing .fit files

### ISSUE THREAD

**Issue by fellrnr** [pe-st/garmin-connect-export#25]
The script failed when repeating a download, not ignoring the existing files correctly, 
I added this at line 908 which solved the problem for me, though it's not elegant. 
           elif isfile(args.directory + '/activity_' + str(actvty['activityId']) + '.fit'):
                pass
                # Display which entry we're skipping.
                print('//#!JFS!# Skipping Garmin Connect activity (exists)')

**Comment by pe-st** [comment]
I could reproduce the problem and then fix it. Thanks for reporting it!
