### ISSUE TITLE
Feature request - new parameter: --workflowdirectory

### ISSUE THREAD

**Issue by telemaxx** [pe-st/garmin-connect-export#28]
currently i still use:  [repro from rsjrny](https://github.com/rsjrny/Garmin-Connect-Export/)
The advantage is/was Pathon3 support, but hopefully youre repro is soon also p3 compatible...
For this repro i have implemented a new parameter `-w --workflowdirectory`
https://github.com/rsjrny/Garmin-Connect-Export/pull/4/files

i use that function for postprocessing my activities with "mytourbook"
mytourbook imports the file from that directory and removes that file after that.
but it stays in the `-d  --directory` folder and will not be downloaded again.

what do you think about that function? should i implement it also for youre repro?

the disadvantage of [rsjrny](https://github.com/rsjrny/Garmin-Connect-Export/) is the broken github history. seem so that the author has not started with a fork.

**Comment by pe-st** [comment]
I had a brief look at your PR for the repo of @rsjrny (yes, it's a pity they didn't fork properly, it makes comparing the differences much harder). IIUC you'd like two things:
- have a better descriptive name than just the existing `--desc` option
- making a copy of the downloaded data file (in your case the `.fit` file) in a specified directory

I think that would be a welcome addition, but I would maybe separate into two options, one for the filename and one for the copy into the workflow directory.

**Comment by telemaxx** [comment]
i just googled what IIUC means ;-)
@rsjrn fork had not the --desc option. therefore i renamed the files. --desc i could use, for this also. maybe extend with device name.

**Comment by telemaxx** [comment]
the second point is what I want. but without the number part of the original file name.

**Comment by telemaxx** [comment]
like this:
2020-03-12T17-01-41-Hannover_Cycling-Edge_530.fit

**Comment by telemaxx** [comment]
now i have  a working version with '--workflowdirectory'
should i send a PR into you're p3 branch?

i have now switched from  [repro from rsjrny](https://github.com/rsjrny/Garmin-Connect-Export/) to that version on my raspberry pi...

```

 -w [WORKFLOWDIRECTORY], --workflowdirectory [WORKFLOWDIRECTORY]
                        if downloading activity(format: 'original' and
                        --unzip): copy the file, given a friendly filename, to
                        this directory (default: not copying)
  --wdesc [WDESC]       append the activity's description to the file name of
                        the workflow file; limit size if number is given,
                        default 20
  --wdevice [WDEVICE]   append the activity's device-name to the file name of
                        the workflow file; limit size if number is given,
                        default 10


```

**Comment by telemaxx** [comment]
i close this ticket,  because i have made a pr which implemented this
