### ISSUE TITLE
file prefix (-fp) wont work with "-f original"

### ISSUE THREAD

**Issue by telemaxx** [pe-st/garmin-connect-export#29]
`fit_filename` is not really used.
`fit_filename = directory + '/' + prefix + 'activity_' + activity_id + append_desc + '.fit'`
with `-f gpx` it is ok.
i will fix that with the next PR for workflow mode

**Comment by pe-st** [comment]
Thanks for spotting that one.

`fit_filename` is only used to check if the file was already download. But this check only works for `.fit` files (original files can also be the very old Garmin `.tcx` format or manually uploaded `.gpx` files)

Only when downloading the zip and unzipping it you can know the real extension of the original file.

This was an easy enough error to fix, so I corrected it on my p3 branch...

**Comment by telemaxx** [comment]
fixed in latest p3 branch
