### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 16: ordinal not in range(128)

### ISSUE THREAD

**Issue by cpiekacz** [pe-st/garmin-connect-export#39]
I get this error when the script is run by cron. Works fine when running manually in shell.

```
Welcome to Garmin Connect Exporter!
Connecting to Garmin Connect... Done.
Requesting Login ticket... Done. Ticket=###
Authenticating... Done.
Querying list of activities 1..3... Done.
Garmin Connect activity (1/3) [4984080154] Traceback (most recent call last):
  File "gcexport.py", line 1005, in <module>
    main(sys.argv)
  File "gcexport.py", line 913, in main
    print(actvty['activityName'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 16: ordinal not in range(128)
```

**Comment by telemaxx** [comment]
seems so that you use a old version 2.x
maybe you're cron using a old version and manually started a different version?

**Comment by telemaxx** [comment]
u'\xf3 is the special char in Fenix.

**Comment by cpiekacz** [comment]
The script is running on 2.7 both from the cron and in the shell. It fails on `ImportError: cannot import name 'urlencode' from 'urllib'` when run on python3. 

I suppose the problem is with handling utf8 chars with ascii-only functions, but I don't code in python so I'm not sure.

**Comment by telemaxx** [comment]
https://github.com/rsjrny/Garmin-Connect-Export/issues/3

**Comment by telemaxx** [comment]
with version 2.x i ment the script version,  not the python version. sorry my comment was not clear. the current script version runs also with python3 and Fenix watches.

**Comment by telemaxx** [comment]
and default branch has changed to master.

**Comment by cpiekacz** [comment]
Ugh, I didn't notice that there is a new version. Updated to the 3.0.1, the bug is still there on python2.7, but on python3 it's gone. Thanks a lot for pointers and such prompt answers!

**Comment by pe-st** [comment]
> Ugh, I didn't notice that there is a new version. Updated to the 3.0.1, the bug is still there on python2.7, but on python3 it's gone. Thanks a lot for pointers and such prompt answers!

Hello @cpiekacz , can you post the traceback of the error when running the latest script with Python 2.7.x? It is supposed to work also with 2.7.x (at least it does for me).

And can you tell me the exact python version and maybe post the log entries (usually a file `gcexport.log` is written) of your problem? The python version you can find in the logfile as well, e.g. for it writes:
```
2020-05-23 14:08:19,672 [INFO   ] Starting gcexport.py version 3.0.1, using Python version 2.7.17
```

**Comment by telemaxx** [comment]
errors only with Fenix watches https://github.com/pe-st/garmin-connect-export/commit/a211c9de124c8ad245696dc43b41e598adbc7e80

**Comment by telemaxx** [comment]
next week i can recheck, i have a fenix

**Comment by cristian5th** [comment]
Remember: this is only an issue when the script is executed via Cron or other similar daemons. If it is executed directly on the terminal, there will be no error.

**Comment by pe-st** [comment]
> Remember: this is only an issue when the script is executed via Cron or other similar daemons. If it is executed directly on the terminal, there will be no error.

That points to the issue I'd like to have more information about. What is different when you run the script from cron? As I have a fēnix and had never issues from the terminal with Python 2.7 and the `ē` in `fēnix` or emojis in the activity title.

Can you add this line to the script in line 848 (just after the `logging.info("Starting`... line)
```
    logging.info("Environment %s", os.environ)
```
and see if there are differences in the logfile when you run from the terminal or from cron? I could imagine there might be differences regarding the `LC_xxx` variables?

(note: be careful with posting the content of the environment, it might contain information you'd rather not share)

**Comment by cristian5th** [comment]
@pe-st , you are not going to believe this: I got myself into the SSL issue, again.

This is when executed directly at the terminal:

> 2020-05-29 19:46:09,889 [INFO   ] Environment environ({'TERM_PROGRAM': 'Apple_Terminal', 'PYENV_ROOT': '/Users/username/.pyenv', 'TERM': 'xterm-256color', 'SHELL': '/bin/zsh', 'TMPDIR': '/var/folders/3j/n7cfz8nd6w9b5t1_9ftgp4k40000gn/T/', 'TERM_PROGRAM_VERSION': '433', 'TERM_SESSION_ID': '5EC6216D-30AE-4214-A4EA-E3E083FB5EE7', 'PYENV_VERSION': '3.8.2', 'USER': 'username', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.zdfycM5VW4/Listeners', 'PYENV_DIR': '/Users/username/dev/python/garmin-connect-export', 'PATH': '/Users/username/.pyenv/versions/3.8.2/bin:/usr/local/Cellar/pyenv/1.2.18/libexec:/Users/username/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin', 'PWD': '/Users/username', 'PYENV_HOOK_PATH': '/Users/username/.pyenv/pyenv.d:/usr/local/Cellar/pyenv/1.2.18/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks', 'XPC_FLAGS': '0x0', 'XPC_SERVICE_NAME': '0', 'HOME': '/Users/username', 'SHLVL': '2', 'PYENV_SHELL': 'zsh', 'LOGNAME': 'username', 'LC_CTYPE': 'UTF-8', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0'})

And this is when executed by Cron:

> 2020-05-29 19:52:01,986 [INFO   ] Environment environ({'SHELL': '/bin/zsh', 'TMPDIR': '/var/folders/3j/n7cfz8nd6w9b5t1_9ftgp4k40000gn/T/', 'USER': 'username', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PWD': '/', 'XPC_FLAGS': '0x0', 'XPC_SERVICE_NAME': '0', 'SHLVL': '1', 'HOME': '/Users/username', 'LOGNAME': 'username', '_': '/usr/bin/python3', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'SDKROOT': '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk', 'CPATH': '/usr/local/include', 'LIBRARY_PATH': '/usr/local/lib', '__PYVENV_LAUNCHER__': '/Library/Developer/CommandLineTools/usr/bin/python3', 'LC_CTYPE': 'UTF-8'})

I see many differences but I cannot help you interpret them, only that it is not using the same Python version.

When I executed it via Cron, I got the SSL certificate error as we discussed in issue #40 

> <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>

But I see that the Python being called by Cron is not the one I installed. It is calling the one that came with Mac OS Catalina. Any suggestion about how to make Cron use the right version of Python? For the record, the right version has been configured to be the default; meaning that, if I type python -V at the terminal, I correctly get 3.8.2. But when python is called by Cron, 2.7 is used when the command is python and 3.7 is used when the command is python3.

What a mess!

**Comment by cristian5th** [comment]
You know what? I believe there is no problem once again and the issue is being caused by the installation of Python.

I changed my task in Cron, forcing it to use the Python version that I want, and when executed, it gave me the same environment as when executed via the terminal.

> 2020-05-29 21:53:00,342 [INFO   ] Environment environ({'PYENV_ROOT': '/Users/username/.pyenv', 'SHELL': '/bin/zsh', 'TMPDIR': '/var/folders/3j/n7cfz8nd6w9b5t1_9ftgp4k40000gn/T/', 'PYENV_VERSION': '3.8.2', 'USER': 'username', 'PYENV_DIR': '/Users/username/dev/python/garmin-connect-export', 'PATH': '/Users/username/.pyenv/versions/3.8.2/bin:/usr/local/Cellar/pyenv/1.2.18/libexec:/usr/bin:/bin:/usr/sbin:/sbin', 'PWD': '/', 'PYENV_HOOK_PATH': '/Users/username/.pyenv/pyenv.d:/usr/local/Cellar/pyenv/1.2.18/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks', 'XPC_FLAGS': '0x0', 'XPC_SERVICE_NAME': '0', 'HOME': '/Users/username', 'SHLVL': '1', 'LOGNAME': 'username', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'LC_CTYPE': 'UTF-8'})

Notice the __CG_USER_TEXT_ENCODING that was missing before. This might probably be the root of the problem because I just executed the script via Cron with the original `print(actvty['activityName'])` code and I got no issue.

@cpiekacz , you should try calling the full path to the Python executable within the Cron task. It seems to work for me.

**Comment by telemaxx** [comment]
in cron jobs i also always use the full path to the executables.
