### ISSUE TITLE
Bug: existing activities are reloaded again and again

### ISSUE THREAD

**Issue by telemaxx** [pe-st/garmin-connect-export#48]
seems so, that garmin is using are sligtliy different fitfilename
1234567890_ACTIVITY.fit

instead of:
1234567890.fit

so when using:

`-f original `

with:

`--unzip`

it did not detect existing fitfiles

inside:
 `def export_data_file` 
i changed one line from:
        `fit_filename = directory + sep + prefix + 'activity_' + activity_id + append_desc + '.fit'`
to:
        `fit_filename = directory + sep + prefix + 'activity_' + activity_id + '_ACTIVITY' + append_desc + '.fit'`
and add directly behind that line for testing:
        `logging.debug('fitfilename: %s', fit_filename)`

**Comment by pe-st** [comment]
Thanks for reporting this! Apparently Garmin changed the filenames under the hood.

I have made a fix in 3.0.2 which restores the old filenames, so the expected names for the check before downloading should match again.

Can you check if it works for you?

**Comment by telemaxx** [comment]
i check that, an report. and i merge you're current master in my fork and update my open PR

**Comment by telemaxx** [comment]
I have tested it with Python3 and it looks good so far.

**P3: fitfiles with unzip**
`c:\Python3\python.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 10 -f original  --username "myname"  --password "mypasswd" --directory "C:\public\gps" --unzip`

**P3: gpx files**
`c:\Python3\python.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 5 -f gpx --username "myname"  --password "mypasswd" --directory "C:\public\gps"`

**P3: tcx files**
`c:\Python3\python.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 5 -f tcx --username "myname"  --password "mypasswd" --directory "C:\public\gps"`

**P3: gpx files in subfolder**
`c:\Python3\python.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 5 -f gpx   --username "myname"  --password "mypasswd"  --directory "C:\public\gps" -s gpx`

**P3: tcx files in subfolder**
`c:\Python3\python.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 5 -f tcx   --username "myname"  --password "mypasswd"  --directory "C:\public\gps" -s tcx`

**P3: some more advanced parameter**
`c:\Python3\Python.exe C:\Users\top\BTSync\SA5\qpython\scripts\Garmin-Connect-Export-pest\gcexport.py  -c 12 -f tcx --username "myname"  --password "mypasswd"--directory "C:\public\gps" --unzip --desc 12 -fp -sa 8 -s tcx`
