### ISSUE TITLE
 HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by eze-fayu** [pe-st/garmin-connect-export#50]
python version 3.6.9 on linux

console report:

Welcome to Garmin Connect Exporter!
Connecting to Garmin Connect... Done.
[ERROR] Failed to reach url https://sso.garmin.com/sso/signin?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern%2F&webhost=https%3A%2F%2Fconnect.garmin.com&source=https%3A%2F%2Fconnect.garmin.com%2Fen-US%2Fsignin&redirectAfterAccountLoginUrl=https%3A%2F%2Fconnect.garmin.com%2Fmodern%2F&redirectAfterAccountCreationUrl=https%3A%2F%2Fconnect.garmin.com%2Fmodern%2F&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&locale=en_US&id=gauth-widget&cssUrl=https%3A%2F%2Fstatic.garmincdn.com%2Fcom.garmin.connect%2Fui%2Fcss%2Fgauth-custom-v1.2-min.css&clientId=GarminConnect&rememberMeShown=true&rememberMeChecked=false&createAccountShown=true&openCreateAccount=false&displayNameShown=false&consumeServiceTicket=false&initialFocus=true&embedWidget=false&generateExtraServiceTicket=true&generateTwoExtraServiceTickets=false&generateNoServiceTicket=false&globalOptInShown=true&globalOptInChecked=false&mobile=false&connectLegalTerms=true&locationPromptShown=true&showPassword=true#, error: HTTP Error 401: Unauthorized
Requesting Login ticket...Traceback (most recent call last):
  File "gcexport.py", line 1061, in <module>
    main(sys.argv)
  File "gcexport.py", line 863, in main
    login_to_garmin_connect(args)
  File "gcexport.py", line 514, in login_to_garmin_connect
    login_response = http_req_as_string(URL_GC_LOGIN + '#', post_data, headers)
  File "gcexport.py", line 271, in http_req_as_string
    return http_req(url, post, headers).decode()
  File "gcexport.py", line 247, in http_req
    response = OPENER.open(request, data=post)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by pe-st** [comment]
Hello @eze-fayu, I get exactly the same error if I mistype my password (The `HTTP Error 401: Unauthorized` hints at a failed authentication), but with the correct password the script still works.

**Comment by eze-fayu** [comment]
such a dumb!!!! you' right, i forgot a caps on the password. Thanks!!!!
