### ISSUE TITLE
Payment Required?

### ISSUE THREAD

**Issue by sgowtham** [pe-st/garmin-connect-export#54]
Greetings.

Is anyone else encountering the Payment Required message/error after authentication?

`[ERROR] Failed to reach url https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities?start=0&limit=1, error: HTTP Error 402: Payment Required`

Everything was fine as of last night.

My best,
Gowtham

**Comment by reto** [comment]
Hi, i have the same problem. Exactly the same. For the first time today. I have a cron job fetching my activities. I hope tomorrow it will work again.

**Comment by pierretamisier** [comment]
I have exactly the same issue too.

**Comment by reto** [comment]
My cron job runs every 4hr. All of them failed now with this exact message. 😕

**Comment by magalive1991** [comment]
same error from today, before it was working fine...

**Comment by sidddy** [comment]
there's a good hint in https://github.com/tcgoetz/GarminDB/issues/109#issuecomment-785047086 and adding that mentioned header in various requests indeed seems to fix this issue.

**Comment by telemaxx** [comment]
i have just added this line to my fork. seems to solve this problem.

**Comment by pierretamisier** [comment]
same here. PR https://github.com/pe-st/garmin-connect-export/pull/55 works for me.

**Comment by pe-st** [comment]
Should be fixed by the PR #55, I released v3.0.3
