### ISSUE TITLE
issue on username and password

### ISSUE THREAD

**Issue by TheKiteRunning** [pe-st/garmin-connect-export#6]
Hi, thank you very much for your work!

the username in your readme file is not an email, however, an email address is required in my garmin login page.

Besides, I don‘t know why but I can't type my password in the command window

Looking forward to your reply.

**Comment by pe-st** [comment]
@TheKiteRunning It seems that for some accounts the email address is needed and for others not. I can login with both username and email address.

And I suppose that when you say you can't type the password means the command window displays a `Traceback`? You spotted an error :wink:, thanks for reporting it! It should be fixed now.
