### ISSUE TITLE
Login refused with Python 2.7

### ISSUE THREAD

**Issue by pe-st** [pe-st/garmin-connect-export#64]
When trying to understand https://github.com/pe-st/garmin-connect-export/issues/60 I noticed that the exact same login request works with Python 3.x (3.9 in my case) and fails with Python 2.7.18

With Python 2.7.18 the request for a login ticket fails with HTTP status 403 (forbidden).

Somewhere between 2021-05-09 (of when I have a log of a successful request) and 2021-05-27 (issue #60 created) something must have changed on Garmin's servers.

I'm not an expert and haven't found so far what exactly is different between HTTP requests from Python 2.7 and Python 3.x

**Comment by moderation** [comment]
Python 2 was sunsetted on Jan 1 2020 and is no longer supported - https://www.python.org/doc/sunset-python-2/

I removed Python 2 support in my fork years ago - https://github.com/moderation/garmin-connect-export

Do you have enough users who can't or work upgrade to Python 3 to justify the troubleshooting time and support?

**Comment by pe-st** [comment]
Version 3.2.0 now explicitly denies working with Python 2.x

If you're impacted by this change (no possibility to upgrade to Python 3.x) I'm afraid you'll have to solve/work around this issue yourself. I neither have the time nor the knowledge to make the script work again with Python 3.x and as @moderation mentioned Python 2.7 hasn't officially been supported any more for more than 18 months.
