### ISSUE TITLE
Just fyi: Getting all activities via Garmin Data Export

### ISSUE THREAD

**Issue by mipapo** [pe-st/garmin-connect-export#7]
Garmin has released a tool to to be GDPR compatible:
https://www.garmin.com/en-US/account/datamanagement/exportdata/
It only took some minutes to get the Download: In the download file you will find in the folder "DI_CONNECT"-> "DI-Connect-Fitness" in the files "UploaedFiles_....*.zip"

Just extract the zip file and you get all your fit files

**Comment by pe-st** [comment]
@mipapo Thanks for telling, didn't know that.
There is also some meta information present in the `username...summarizedActivities.json` file, but not in the same format as the export script gets from Garmin Connect.

**Comment by pe-st** [comment]
@mipapo Mentioned the link in the README
