### ISSUE TITLE
Only able to download 1 activity

### ISSUE THREAD

**Issue by Only1nr7** [pe-st/garmin-connect-export#70]
I used version 3.0.3 until it stopped working. Now using version 3.3.0 but I can only download 1 activity instead of all (over 2000 activities). What goes wrong, I'm quite new to Python and I'm trying to understand but can't understand. The result that I get is:

Connecting to Garmin Connect... Done.
Requesting Login ticket... Done. Ticket=ST-04883869-IcK67OckuWlLoiqyNrqE-cas
Authenticating... Done.
Getting display name... Done. displayName=############
Fetching user stats... Done.
Querying list of activities 1..1... Done.
Downloading: Garmin Connect activity (1/1) [#########] Zutphen Wandelen
	2022-01-02T12:04:50+01:00, 00:30:49, 2.462km
	Data file already exists; skipping...
Done!

Do I have to change some lines to pass this problem?

**Comment by Only1nr7** [comment]
I have found it, updated the number in line 503 to download multiple files.

**Comment by lowtower** [comment]
1 is the default value for the number of activities.
You can "override" it with the parameter -c or --count (e.g. -c 2000)

**Comment by pe-st** [comment]
Hello @Only1nr7, as @lowtower correctly wrote you should use the `-c` option to download multiple activities.

The first example in the README (<https://github.com/pe-st/garmin-connect-export#examples>) is the one to download all activities:

```bash
python gcexport.py --count all
```
