### ISSUE TITLE
Is it possible to filter only on one activity type ID?

### ISSUE THREAD

**Issue by Only1nr7** [pe-st/garmin-connect-export#71]
I would like to export only the Running activities. Is that possible? And if so, how to do that?

**Comment by pe-st** [comment]
Hello @Only1nr7, this is currently not possible, but it should not be very difficult to implement.

**Comment by Only1nr7** [comment]
Hi @pe-st, thank you for your reply. I think this would be helpful, at least for me. I record a lot of activities in Garmin but the walking, hiking, skiing etc are just for fun. For the running part I take the details from the export and use this in an Excel file to analyze my activities in more detail and try to see where I can improve. Of course I can delete these afterwards but the script would finish a lot faster without that other data.
I will keep an eye on the releases to see if this will be added. Also without that I'm already very happy with your work. Just started on Python last year as my first language. So enough to learn....

**Comment by joetimmerman** [comment]
@Only1nr7 see PR #72

**Comment by gael-ft** [comment]
Hi @pe-st, thanks for the project !

Any chance this issue (and related PR) will be merged / closed ?
I believe this would be useful in various use cases

**Comment by pe-st** [comment]
@gael-ft I've added it to https://github.com/pe-st/garmin-connect-export/pull/104

**Comment by pe-st** [comment]
#104 is now merged as version 4.3
