### ISSUE TITLE
Download summary data

### ISSUE THREAD

**Issue by Dave-DigiMim** [pe-st/garmin-connect-export#84]
Hi was using Garpy  but it no longer lets me connect . 
They have a nice feature to download the summary which includes a laps.csv  which I find most useful.
Could this option be included ?

**Comment by pe-st** [comment]
Hello
I never used garpy so I don't know what the `laps.csv` contains. Do you have an example or can you describe what kind of information you would like to have?

**Comment by Dave-DigiMim** [comment]
I have got myself so confused over the years, between using garpy , garmin-backup and gcexport swopping between them due to garmin blocking access... it appears that I actually extract the laps from the fit file.. Yours is named differently so my fit file parser did not pick it. 
So not to worry i think i have sorted it..
