### ISSUE TITLE
Oracle Free tier 403 Forbidden

### ISSUE THREAD

**Issue by Dave-DigiMim** [pe-st/garmin-connect-export#90]
I just signed up for Oracle free tier . It works really well and I thought I could move my Garmin reporting to it..
However I got the below error and it seems because both are hosted on Cloudflare they will not allow it.. Seems a bit unfair.
Not much i guess I can do!
[INFO] Requesting Login ticket
[ERROR] Server couldn't fulfill the request, code 403, error: HTTP Error 403: Forbidden
[INFO] Headers returned:
Date: Thu, 04 May 2023 06:49:36 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 16
Connection: close
X-Frame-Options: SAMEORIGIN
Referrer-Policy: same-origin
Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=Dy%2B0kmsx05cWdq7BG%2F2qiJ3vzDoV5EPP4QQshcSDT%2BglKxWWInn0aTxmsJ%2BVGWQFXs64e6TvUO66%2FOnydcFNDkSz%2BjNxmizQaQTRUWzHd8Uei3EEhIJtEyay0pHLy9U8"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
Vary: Accept-Encoding
Server: cloudflare
CF-RAY: 7c1ece02ff0a9cda-JNB

**Comment by pe-st** [comment]
I don't use the Oracle Cloud, and I have never seen this 403 myself with Garmin Connect. Maybe Oracle Cloud Support has an idea?

**Comment by Dave-DigiMim** [comment]
I think it is Garmin who stop the connection. I really just put this here as a warning that it does not work. I like the speed and storage I get on the Oracle free tier .. I am now using my Pihole to download the file and scp it to the Oracle.
