### ISSUE TITLE
Error 403- Forbidden

### ISSUE THREAD

**Issue by themeek123** [pe-st/garmin-connect-export#98]
Receiving this error since last successful use on 23 Sept 2023. 
I see this error was listed before but it seemed to resolve itself. Not so after nearly 2 weeks
Any help appreciated, i am a "user" so don't have the skills to troublehsoot. 

No Windows 10 updates since well before error started. No changes to PC that i know (single user laptop). 
I can login on the Garmin website/APP with same details. 
Python 392

Many thanks in advance

Authenticating... Done.
[ERROR] Failed to reach url https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities?start=0&limit=17, error: HTTP Error 403: Forbidden
Querying list of activities 1..17...Traceback (most recent call last):
{then a long list of errors}

**Comment by telemaxx** [comment]
i think it is the same as reported in issue #94 and #95

**Comment by themeek123** [comment]
Thanks for the reference. No idea where I was searching. Only found one thread on that topic. There are plenty !!Will work through the comments/solutions. On 6 Oct 2023, at 13:36, Thomas Th. ***@***.***> wrote:﻿
i think it is the same as reported in issue #94 and #95

**Comment by pe-st** [comment]
Do you still have the issue with the new version 4.2.0?

**Comment by telemaxx** [comment]
@pe-st just merged the fix for this problem...

**Comment by themeek123** [comment]
Thanks for following up. I haven’t had chance to look at it yet. I usually need a good few hours for this sort of thing! Thanks again. On 8 Oct 2023, at 16:33, Peter Steiner ***@***.***> wrote:﻿
Do you still have the issue with the new version 4.2.0?

**Comment by themeek123** [comment]
Managed to get 4.2.0 to work. Absolutely brilliant, thanks @pe-st 
First time for me to use PyPi, pip command, and to find Garth module.  
Just over an hour this time! I've spent hours and hours on the mods like this before!!

**Comment by ChristianRohde** [comment]
nice work. I briefly had a look in #95 and at the end it sounds that the issue got solved. So installing the latest version will be the solution? Based on the changelog of my downloaded version I was using version 3.0.3 - 2021-02-24 until it broke. Are there more changes in the output of the overview table we get from Garmin with the new version? So far this seems to be undocumented and I just have to find out I guess
